checking connection

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,19 @@ jobs:
           port: 22
           debug: true
           script: | 
-            whoami
-            pwd
+            set -e
+
+            export NVM_DIR="$HOME/.nvm"
+
+            if [ -s "$NVM_DIR/nvm.sh" ]; then
+              source "$NVM_DIR/nvm.sh"
+            else
+              echo "ERROR: NVM is not installed at $NVM_DIR"
+              exit 1
+            fi
+
+            echo "Node:"
             node -v
+
+            echo "NPM:"
             npm -v
